# Generated by Django 5.1.3 on 2024-11-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostico", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="cnpj",
            field=models.CharField(max_length=100, verbose_name="CNPJ"),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="nmrContato",
            field=models.CharField(max_length=100, verbose_name="Número de Contato"),
        ),
    ]
