# Generated by Django 5.1.3 on 2024-11-19 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0005_alter_empresa_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='usuario',
        ),
    ]
