# Generated by Django 5.1.3 on 2024-12-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0007_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
